# Generated by Django 2.2.2 on 2019-11-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(max_length=50)),
                ('house_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('house_addproj', models.CharField(max_length=50)),
                ('house_fixtures', models.CharField(max_length=200)),
                ('house_property', models.CharField(max_length=200)),
                ('house_garage', models.CharField(max_length=50)),
                ('house_state', models.CharField(max_length=50)),
            ],
        ),
    ]
