# Generated by Django 2.2.2 on 2019-12-07 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20191201_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
